<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        \Illuminate\Support\Facades\DB::table('users')->truncate();

        \Illuminate\Support\Facades\DB::table('users')->insert([
            [
                'id' => 1,
                'idNumber' => '034202001601',
                'username' => 'tranvanan',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Trần Văn An',
                'gender' => 1,
                'imgIdCardFront' => 'https://1.bp.blogspot.com/-K2hIUZBrF5M/Xmx6B67iB9I/AAAAAAAADNo/P9JhX-dRf3ELkiBZCJ87SbbYO4v9uculQCEwYBhgL/s1600/PSD%2BCMND%2BNAM%2B2%2BM%25E1%25BA%25B6T%2B3567.png',
                'imgIdCardBack' => 'https://1.bp.blogspot.com/-K2hIUZBrF5M/Xmx6B67iB9I/AAAAAAAADNo/P9JhX-dRf3ELkiBZCJ87SbbYO4v9uculQCEwYBhgL/s1600/PSD%2BCMND%2BNAM%2B2%2BM%25E1%25BA%25B6T%2B3567.png',
                'age' => 20,
                'phone' => '012341234',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 2,
                'idNumber' => '034202001602',
                'username' => 'tranvanduc',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Trần Văn Đức',
                'gender' => 1,
                'imgIdCardFront' => 'https://1.bp.blogspot.com/-K2hIUZBrF5M/Xmx6B67iB9I/AAAAAAAADNo/P9JhX-dRf3ELkiBZCJ87SbbYO4v9uculQCEwYBhgL/s1600/PSD%2BCMND%2BNAM%2B2%2BM%25E1%25BA%25B6T%2B3567.png',
                'imgIdCardBack' => 'https://1.bp.blogspot.com/-K2hIUZBrF5M/Xmx6B67iB9I/AAAAAAAADNo/P9JhX-dRf3ELkiBZCJ87SbbYO4v9uculQCEwYBhgL/s1600/PSD%2BCMND%2BNAM%2B2%2BM%25E1%25BA%25B6T%2B3567.png',
                'age' => 24,
                'phone' => '012561234',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 3,
                'idNumber' => '034202001603',
                'username' => 'trandinhanh',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Nguyễn Đình Anh',
                'gender' => 1,
                'imgIdCardFront' => 'https://1.bp.blogspot.com/-B30BI8l1hQQ/XQYA-MWcKkI/AAAAAAAACwc/2dUSha_FwBwZSEABwYNzRuzuG-tJQgwgQCEwYBhgL/s1600/CMND-N%25E1%25BB%25AE-NGUY%25E1%25BB%2584N-T%25E1%25BB%2588NH-59.jpg',
                'imgIdCardBack' => 'https://1.bp.blogspot.com/-B30BI8l1hQQ/XQYA-MWcKkI/AAAAAAAACwc/2dUSha_FwBwZSEABwYNzRuzuG-tJQgwgQCEwYBhgL/s1600/CMND-N%25E1%25BB%25AE-NGUY%25E1%25BB%2584N-T%25E1%25BB%2588NH-59.jpg',
                'age' => 19,
                'phone' => '012356234',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 4,
                'idNumber' => '034202001604',
                'username' => 'nguyenvandung',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Nguyễn Văn Dũng',
                'gender' => 1,
                'imgIdCardFront' => 'https://1.bp.blogspot.com/-B30BI8l1hQQ/XQYA-MWcKkI/AAAAAAAACwc/2dUSha_FwBwZSEABwYNzRuzuG-tJQgwgQCEwYBhgL/s1600/CMND-N%25E1%25BB%25AE-NGUY%25E1%25BB%2584N-T%25E1%25BB%2588NH-59.jpg',
                'imgIdCardBack' => 'https://1.bp.blogspot.com/-B30BI8l1hQQ/XQYA-MWcKkI/AAAAAAAACwc/2dUSha_FwBwZSEABwYNzRuzuG-tJQgwgQCEwYBhgL/s1600/CMND-N%25E1%25BB%25AE-NGUY%25E1%25BB%2584N-T%25E1%25BB%2588NH-59.jpg',
                'age' => 30,
                'phone' => '012357634',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 5,
                'idNumber' => '034202001605',
                'username' => 'nguyenvandung',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Nguyễn Văn Dũng',
                'gender' => 1,
                'imgIdCardFront' => 'https://1.bp.blogspot.com/-B30BI8l1hQQ/XQYA-MWcKkI/AAAAAAAACwc/2dUSha_FwBwZSEABwYNzRuzuG-tJQgwgQCEwYBhgL/s1600/CMND-N%25E1%25BB%25AE-NGUY%25E1%25BB%2584N-T%25E1%25BB%2588NH-59.jpg',
                'imgIdCardBack' => 'https://1.bp.blogspot.com/-B30BI8l1hQQ/XQYA-MWcKkI/AAAAAAAACwc/2dUSha_FwBwZSEABwYNzRuzuG-tJQgwgQCEwYBhgL/s1600/CMND-N%25E1%25BB%25AE-NGUY%25E1%25BB%2584N-T%25E1%25BB%2588NH-59.jpg',
                'age' => 35,
                'phone' => '012365434',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 6,
                'idNumber' => '034202001606',
                'username' => 'nguyenthidung',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Nguyễn Thị Dung',
                'gender' => 2,
                'imgIdCardFront' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'imgIdCardBack' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'age' => 22,
                'phone' => '012365334',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 7,
                'idNumber' => '0342020016010',
                'username' => 'nguyenthihang',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Nguyễn Thị Hằng',
                'gender' => 2,
                'imgIdCardFront' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'imgIdCardBack' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'age' => 19,
                'phone' => '012365234',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 8,
                'idNumber' => '034202001632',
                'username' => 'levantam',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Lê Văn Tám',
                'gender' => 1,
                'imgIdCardFront' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'imgIdCardBack' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'age' => 23,
                'phone' => '033365234',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 9,
                'idNumber' => '034202001633',
                'username' => 'trandinhduc',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Trần Đình Đức',
                'gender' => 1,
                'imgIdCardFront' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'imgIdCardBack' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'age' => 29,
                'phone' => '033565234',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 10,
                'idNumber' => '034202001610',
                'username' => 'tranthithanh',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Trần Thị Thanh',
                'gender' => 2,
                'imgIdCardFront' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'imgIdCardBack' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'age' => 19,
                'phone' => '033775234',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 11,
                'idNumber' => '034202001611',
                'username' => 'lethihoa',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Lê Thị Hòa',
                'gender' => 2,
                'imgIdCardFront' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'imgIdCardBack' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'age' => 31,
                'phone' => '033725234',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 12,
                'idNumber' => '034202001612',
                'username' => 'phamvanduc',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Phạm Văn Đức',
                'gender' => 1,
                'imgIdCardFront' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'imgIdCardBack' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'age' => 40,
                'phone' => '033752347',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 13,
                'idNumber' => '034202001613',
                'username' => 'phamvandung',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Phạm Đức Dũng',
                'gender' => 1,
                'imgIdCardFront' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'imgIdCardBack' => 'https://startuanit.net/wp-content/uploads/2020/04/Share-psd-cmnd-nu.jpg',
                'age' => 32,
                'phone' => '033752342',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 14,
                'idNumber' => '034202001614',
                'username' => 'tranthikhanh',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Trần Thị Khánh',
                'gender' => 2,
                'imgIdCardFront' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'imgIdCardBack' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'age' => 21,
                'phone' => '034752342',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 15,
                'idNumber' => '034202001615',
                'username' => 'nguyenhoainam',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Nguyễn Hoài Nam',
                'gender' => 1,
                'imgIdCardFront' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'imgIdCardBack' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'age' => 24,
                'phone' => '035752342',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 16,
                'idNumber' => '034202001616',
                'username' => 'dovandung',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Đỗ Văn Dũng',
                'gender' => 1,
                'imgIdCardFront' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'imgIdCardBack' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'age' => 28,
                'phone' => '034752342',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 17,
                'idNumber' => '034202001617',
                'username' => 'tranvanhuy',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Trần Văn Huy',
                'gender' => 1,
                'imgIdCardFront' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'imgIdCardBack' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'age' => 31,
                'phone' => '034052342',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 18,
                'idNumber' => '034202001645',
                'username' => 'tranthibay',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Trần Thị Bảy',
                'gender' => 2,
                'imgIdCardFront' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'imgIdCardBack' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'age' => 34,
                'phone' => '035752342',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 19,
                'idNumber' => '034202001646',
                'username' => 'nguyenvanduy',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Nguyễn Văn Duy',
                'gender' => 1,
                'imgIdCardFront' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'imgIdCardBack' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'age' => 19,
                'phone' => '035352342',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ],[
                'id' => 20,
                'idNumber' => '034202001620',
                'username' => 'tranvanduc',
                'password_hash' => '$2y$10$OSkIF0eSpYEFk1szucdRf.cbp8PVuFOR.mGr/tqTKoiWex2nD2Ja2',
                'email' => 'vandung@gmail.com',
                'fullName' => 'Trần Văn Đức',
                'gender' => 1,
                'imgIdCardFront' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'imgIdCardBack' => 'https://vutienblog.com/wp-content/uploads/2018/08/fake-cmnd.jpg',
                'age' => 27,
                'phone' => '035252342',
                'address' => 'Số nhà 18, Đường Lê Đức Thọ',
                'ward' => 'Phường Láng Thượng',
                'district' => 'Quận Đống Đa',
                'city' => 'Hà Nội',
                'created_at' => \Illuminate\Support\Carbon::now(),
                'updated_at' => \Illuminate\Support\Carbon::now(),

            ]
        ]);
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 1');

    }
}
